# Generated by Django 5.0 on 2025-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_kids_friendly', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pet_images/')),
            ],
        ),
    ]
